### ISSUE TITLE
"Files": store an object on file

### ISSUE THREAD

**Issue by andrea-dintino** [dyne/restroom-mw#117]
A statement that stores zenroom's output to a file, it should overwrite an existing file: 

```
Scenario 'ecdh': Create the keypair
Given that I am known as 'Alice'
When I create the keypair
Then print 'keypair'

Then store 'keypair' in the file '/home/stuff/restroom-mw/contracts'
```

**Comment by albertolerda** [comment]
PR #119

**Comment by andrea-dintino** [comment]
@albertolerda @puria 

Currently in order to store a file, we need to print out the file location, which I believe is undesirable for security reasons. 

I think (!) I solution could be to add a statement like 

`Given I have an output file named  'myFile'`

that looks in the input for: 

```
{
"myFile": "./consensusroom-announce.json"  
}
```
