### ISSUE TITLE
Cron job in Restroom-mw

### ISSUE THREAD

**Issue by andrea-dintino** [dyne/restroom-mw#134]
a statement that executes a smart contract every 'seconds', starting from the statement after the 'cron' statement, like: 

```
Given I have a 'number' named 'seconds'
Given I this scripts is triggered every 'seconds'
Given I execute parallel GET to array 'myArray' and save the result named 'myResult' within the object 'myObject'
Then print the 'myObject'
```

input:

```
{
	"seconds": 300,
	"myArray": [
		"http://apiroom.net:3312/",
		"http://apiroom.net:3312/",
		"http://apiroom.net:3312/",
		"http://apiroom.net:3312/"
	]
}
```

**Comment by puria** [comment]
Guess that this should be handled by a consumer/client.

So the client calls an endpoint every x... Or you need something that a consumer attach to (a stream) and receives updates? In that case Rest is not the way to do that.

**Comment by jaromil** [comment]
I don't think this should be in restroom but a api endpoint feature of apiroom.
