### ISSUE TITLE
http middleware does not work as expected

### ISSUE THREAD

**Issue by puria** [dyne/restroom-mw#18]
Contract used:

```gherkin
Rule unknown ignore
Scenario 'ecdh': Create the keypair
Given that I have an endpoint named "myEndpoint"
Given that I connect to "myEndpoint" and save the output
Then print data
Then print the "output"
```
with the following data:
```json
{
	"myEndpoint": "https://apiroom.net/api/dyneorg/Create-a-keypair"
}
```

The expected result: the middleware should run and fill the `output` field in the json result.

**Comment by puria** [comment]
@andrea-dintino I'm looking at the problem and  in the middleware code the the connection sentece is 
`I connect to {} and save the output` but in the contract you tries you wrote:
`that I connect {} and save the output`, which form do you prefer to maintain?

ah and bouble quotes for the variables are not supported in restroom so eventually `"myEndpoint"` should be `'myEndpoint'`

**Comment by andrea-dintino** [comment]
- I tried both the sentences, none works. We'll look at finalizing the Zencode later. 
- checking with the ' ' too

**Comment by puria** [comment]
Yeah, I know, problem lies somewhere else, probably, looking at it... but which form you want me to use?

**Comment by puria** [comment]
Managed to work with some tweaking the main point is that zenroom does not run with undefined data so:
```gherkin
Rule unknown ignore
Scenario 'ecdh': Create the keypair
Given that I have an endpoint named 'endpoint'
Given I connect to 'endpoint' and save the output
Given I have a 'string dictionary' named 'output' 
Then print the 'output'
```
with 
```json
{ "endpoint": "https://apiroom.net/api/dyneorg/Create-a-keypair" }
````

runs smoothly resulting in 

```json
{
  "output": {
    "Alice": {
      "keypair": {
        "private_key": "wX2DAvnBqoQlb+t9iVO5xhjRK+rkxwTBYQTuIB/6wRw=",
        "public_key": "BEYfqFVASk5m/P2xtEJHR+MnN6QrXkIPWPLwV8Qja21QL3hvHBUljJ258FPhy+vMxGgL03WluoYREsfUmVgyKHM="
      }
    }
  }
}
```
