### ISSUE TITLE
"Given nothing" breaks Restroom-mw script, possible collisions.

### ISSUE THREAD

**Issue by andrea-dintino** [dyne/restroom-mw#237]
Problem:
At the moment, Restroom-mw passes the http headers as input to Zenroom by default. This causes the issues 
- "Given nothing" statement not to work (while it still works in Zenroom)
- This can generate a collisions in inputs (as the data is hardcoded into "http_request": {}

Possible solution: 
- a statement like "Given I read the http request and write it into "http_request"
- a rule read only by Restroom-mw such as "Rule restroom-mw pass http header"

**Comment by puria** [comment]
@andrea-dintino ACK will look at it as soon as I can...

**Comment by jaromil** [comment]
`http_request` is passed to HEAP by restroom-mw hence breaking `given nothing`

zenroom's statement `given nothing` should check for `rule ignore restroom-mw` in stack and if present ignore the `http_request` when checking input

restroom-mw should make sure that `rule ignore restroom-mw` is always present at beginning of stack before calling zenroom

**Comment by matteo-cristino** [comment]
Fixed in 69dae1df2b90346c016aadea221fdd63d86ba2fb

**Comment by jaromil** [comment]
Can we please update apiroom to include this fix?
