### ISSUE TITLE
REPL for Zenroom

### ISSUE THREAD

**Issue by benkoo** [dyne/restroom-mw#245]
I wonder if there is a REPL(Read-Evaulate-Print Loop) library or design pattern designed for Zenroom? Otherwise, it might be useful to build one using the node-REPL (https://nodejs.org/api/repl.html) to help other developers to build front ends for Zenroom/RESTroom.

**Comment by benkoo** [comment]
Thanks for the most speedy reply. I imagine that "RESTROOM" might already been using node-REPL? I have to check.

**Comment by puria** [comment]
@benkoo Not really, that uses internal ABI's via transpiled WASM.
But as a REPL you want to use the binary CLI available on the https://github.com/dyne/Zenroom repo.
Run it as zenroom -z for playing with zencode and zenroom only for the Lua calls docs available on https://dev.zenroom.org/#/pages/zencode-cookbook-intro?id=use-zenroom-by-command-line-cli

But many people now days find it more easy to play on https://apiroom.net for prototype and debug interactively so you can also export the result directly in a working restroom-mw instance.

BTW about the restroom architecture that are just express middleware that executes contracts and exposed on restful-like endpoints. You can find more on https://dyne.org/restroom-mw/#/architecture

**Comment by jaromil** [comment]
@puria rlwrap | zenroom -i is a comfortable repl for the Lua dialect.

we do not have yet a repl for zencode

**Comment by puria** [comment]
@jaromil 😍 awesome more precise answer!

**Comment by jaromil** [comment]
@puria well, I made a mistake, no pipe needed

rlwrap zenroom -i
