### ISSUE TITLE
Zenroom crash in Restroom 

### ISSUE THREAD

**Issue by andrea-dintino** [dyne/restroom-mw#42]
The script: 

```
# The Rule unknown ignore is required when using a restroom-mw statement
Rule unknown ignore 

# we'll need to create a keypair to produce an ECDSA signature later
Scenario 'ecdh': Create the keypair
Given that I am known as 'timestampServer'
Given I have my 'keypair'

# Those are restroom-mw statements: define the endpoints
Given that I have an endpoint named 'timeServer' 

# We need those object to store the output of the endpoints
Given I have a 'number' named 'timestamp'


# Those are restroom-mw statements: connect to endpoints and store their output into Zenroom's objects
Given I connect to 'timeServer' and save the output into 'timestamp'


When I create the signature of 'timestamp' 
When I rename the 'signature' to 'timestamp.signature' 


When I create the copy of 'public key' from dictionary 'keypair'
When I rename the 'copy' to 'public key'

# Printing the output
Then print the 'timestamp'
Then print the 'public key'
Then print the 'timestamp.signature'

```

With the data:

```
{
  "timeServer": "http://apiroom.net:3312",
  "timestampServer": {
    "keypair": {
      "private_key": "mi9nqTAatFaaGYZrToHGGsHrJXyP4MQWcEFN35mGrsE=",
      "public_key": "BNYP6D9E5MX8brrbbc+RmH2k2L+f0v0PBTudRl4+g3x6q5dVEnIrqLK/i5NK6E6c2hY7YtU2mv0X6k4deYvgMPE="
    }
  }
}
```

Results into:

{
  "zenroom_errors": {
    "result": "",
    "logs": " .  System memory manager in use\n .  MUTT print functions in use\n .  ECDH curve is SECP256K1\n .  Memory in use: 301 KB\n .  Rule unknown ignore [W] Zencode pattern ignored: Given that I have an endpoint named 'timeServer'\t1[W] Zencode pattern ignored: Given I connect to 'timeServer' and save the output into 'timestamp'\t1[W] Zencode is missing version check, please add: rule check version N.N.N[W] When I create the signature of 'timestamp'\t2[W]  .  Scenario 'ecdh'[W]  .  Given that I am known as 'timestampServer'[W]  .  Given I have my 'keypair'[W]  .  Given I have a 'number' named 'timestamp'[W]  .  When I create the signature of 'timestamp'[W]  .  \u001b[31;1m[!]\u001b[0m **/zencode.lua:323: attempt to index a number value (local 'A')**[W] {\n    a_GIVEN_in = {},\n    b_WHEN_ack = {\n        keypair = {\n            private_key = octet[32] mi9nqTAatFaaGYZrToHGGsHrJXyP4MQWcEFN35mGrsE=,\n            public_key = octet[65] BNYP6D9E5MX8brrbbc+RmH2k2L+f0v0PBTudRl4+g3x6q5dVEnIrqLK/i5NK6E6c2hY7YtU2mv0X6k4deYvgMPE=\n        },\n        timestamp = 1619703176\n    },\n    c_THEN_out = {}\n}[!] Zencode execution error\n[!] Script:\nZEN:begin()\nZEN:parse([[\n# The Rule unknown ignore is required when using a restroom-mw statement\r\nRule unknown ignore \r\n\r\n# we'll need to create a keypair to produce an ECDSA signature later\r\nScenario 'ecdh': Create the keypair\r\nGiven that I am known as 'timestampServer'\r\nGiven I have my 'keypair'\r\n\r\n# Those are restroom-mw statements: define the endpoints\r\nGiven that I have an endpoint named 'timeServer' \r\n\r\n# We need those object to store the output of the endpoints\r\nGiven I have a 'number' named 'timestamp'\r\n\r\n\r\n# Those are restroom-mw statements: connect to endpoints and store their output into Zenroom's objects\r\nGiven I connect to 'timeServer' and save the output into 'timestamp'\r\n\r\n\r\nWhen I create the signature of 'timestamp' \r\nWhen I rename the 'signature' to 'timestamp.signature' \r\n\r\n\r\nWhen I create the copy of 'public key' from dictionary 'keypair'\r\nWhen I rename the 'copy' to 'public key'\r\n\r\n# Printing the output\r\nThen print the 'timestamp'\r\nThen print the 'public key'\r\nThen print the 'timestamp.signature'\n\n]])\nZEN:run()\n\n[!] **/zencode.lua:285: When I create the signature of 'timestamp'** \n[!] Error detected. Execution aborted.\n[*] Zenroom teardown.\n .  Memory used: 335 KB\n"
  },
  "result": "",
  "exception": "[ZENROOM EXECUTION ERROR]\n\n\nundefined"
}

**Comment by puria** [comment]
Version of restroom libs and zenroom npm ?

I just copy pasted on apiroom and works for me: 
![Screenshot 2021-04-29 at 16 39 58](https://user-images.githubusercontent.com/10379/116569408-a56b3b00-a909-11eb-924d-305373570207.png)

If I run it locally, then some other error comes up... guess is related to the 'number' thingy

**Comment by andrea-dintino** [comment]
Yes, it works on Apiroom, but not if you clone restroom.
