### ISSUE TITLE
Middleware needs to consider (and prepend) the apiroom user folder in the path for contracts in chains

### ISSUE THREAD

**Issue by pasfranc** [dyne/restroom-mw#67]
Reminder for @pasfranc 

- In the chain flow take the user folder path
- pass it into the executeChain
- prepend it before contract names

This change is needed to avoid to specify in yml the user folder i.e. for user "utente":
zenchain: 1.0
name: single-contract
start: utente/keypair.zen
blocks:
---utente/keypair.zen:

**Comment by andrea-dintino** [comment]
Not necessary

**Comment by andrea-dintino** [comment]
Solved with this [example](https://github.com/dyne/restroom-template/blob/master/zencode/chains/chain-http-read-post.yml)
