### ISSUE TITLE
Statement that reads the timestamp via system call and stores it into object

### ISSUE THREAD

**Issue by andrea-dintino** [dyne/restroom-mw#86]
We need a statment like: 

Given that I fetch the local timestamp and store it into "myTimestamp"

Which should output a 10 digits number: 

{
"myTimestamp":  1643913502
}

**Comment by puria** [comment]
@andrea-dintino Noiceeee

**Comment by andrea-dintino** [comment]
Correction: not a 10 digit number, but the full length of the unix time

**Comment by jaromil** [comment]
@puria very cool. Also I think of making a i/o fencing exception in the cli and read epoch to allow profiling

**Comment by puria** [comment]
Excellent idea 👌🏻
